vtex-apps/shelf

CHANGELOG.md, react/global.css
- Fix ProductSummary width on mobile mode 
https://claudivan--storecomponents.myvtex.com/
=> Fix ProductSummary width on mobile mode

CHANGELOG.md, react/queries/productsQuery.gql
Add the `productClusters` property in the query.
The property is now required in the product summary.
=> Add product clusters to graphql query

CHANGELOG.md, react/ShelfContent.js
- Fix ShelfContent ref warning
[workspace](https://claudivan--storecomponents.myvtex.com/)
=> Fix ShelfContent ref warning

CHANGELOG.md, manifest.json, react/ShelfItem.js
- Fix destructuring of undefined in `ShelfItem`.
- Error caused because the referenceId is not required.
https://claudivan2--storecomponents.myvtex.com/
=> Fix destructuring of undefined in `ShelfItem`

CHANGELOG.md, react/ProductList.js, react/RelatedProducts.js, react/Shelf.js
Fixed infinite content loader when products array is loaded but empty.
When a product has no related products, for example, the related products' shelf was shown and the loader never ends.
[Access the workspace](https://estacio--storecomponents.myvtex.com/nintendo-switch/p)
=> Fixed infinite content loader when products array is loaded but empty.

CHANGELOG.md, react/ProductList.js, react/RelatedProducts.js, react/Shelf.js
Added page padding class to allow apps to have the same default padding.
Footer had different padding compared to Shelf.
[Access the worskpace](https://padding--storecomponents.myvtex.com/)
=> Add page padding to match footer and other page components.

CHANGELOG.md, manifest.json, react/Shelf.js
Shelf keep loading when an error happen in the query.
[Access this workspace](https://shelfquery--storecomponents.myvtex.com/), there is an error happening in the query of this workspace, so the shelf shouldn't be rendered.
=> Stop shelf loading when an error happen in the query

CHANGELOG.md, manifest.json, react/ShelfItem.js
We basically do not use header elements (h1, h2, h3) in our components and it is desirable to use these elements to make our html codebase more meaningful (by adding semantic html elements).
`product-summary` `ProductName` in `shelf`  used as H2 element instead of a div.
[Here](https://alves--storecomponents.myvtex.com/)
* [] Bug fix (a non-breaking change which fixes an issue)
=> Set ProductName tag as h2 in Shelf

CHANGELOG.md, manifest.json, react/ShelfItem.js, react/utils/urlHelpers.js
Load image of shelf with width of 500px and not the original size
=> Resize image of shelf for width 500px

CHANGELOG.md, manifest.json, react/ShelfItem.js
What happened before: we sent to product-summary the first item of the sku list given for that slug.
That sku could be unavailable, it only returned in the search query because another sku is indeed available. So now, we search for this available SKU.
Before:
Now:
wks to test:
https://fidelis--pilateslovers.myvtex.com/
https://skulist--storecomponents.myvtex.com/
=> search for available item on sku list

CHANGELOG.md, manifest.json, react/ShelfContent.js
This PR depends on vtex-apps/slider#16
[Here](https://alves--storecomponents.myvtex.com)
**Before**
**After**
=> Fix sliderWidth

CHANGELOG.md, manifest.json, react/ProductList.js, react/RelatedProducts.js, react/ShelfContent.js, react/ShelfItem.js, react/__mocks__/vtex.pixel-manager/PixelContext.js
Sending productClick event to Pixel Manager with the purpose of usage in google-analytics.
**Workspace:** https://aguaviva--storecomponents.myvtex.com/
=> Send productClick events to PixelManager

CHANGELOG.md, manifest.json, react/Shelf.js, react/ShelfContent.js, react/ShelfItem.js, react/propTypes.js
Sending productImpression event to Pixel Manager with the purpose of usage in google-analytics.
A productImpression is an event defined as the moment a user sees a product in a list of products. It occurs before productClick and productDetail events.
**Workspace**: https://aguaviva--storecomponents.myvtex.com/
Related: [pixel-manager#19](https://github.com/vtex/pixel-manager/pull/19)
=> Send productImpression events to PixelManager

CHANGELOG.md, manifest.json, react/ProductList.js, react/RelatedProducts.js, react/__mocks__/vtex.native-types/index.js, react/__test__/Shelf.test.js, react/typings/vtex.native-types.d.ts, store/contentSchemas.json, store/interfaces.json
Moved schema of content properties from components to `contentSchemas.json`
Using the new `vtex.native-types` to support i18n content insertion through `Storefront`
Workspace: https://i18n--storecomponents.myvtex.com/admin/cms/storefront
1 - Click to edit the shelf at storefront sidebar
2 - Edit shelf title and save
3 - Switch language using admin's language switcher
4 - Content should be different for the selected language
=> Add support to i18n content through CMS

CHANGELOG.md, react/ProductList.js
Make ProductList an importable component that can be used in other apps.
I am developing a Wordpress integration app that includes a custom product shelf (products related to a Wordpress article via tagging). Rather than add this very specific shelf type to the Shelf app, the same functionality can be achieved by importing ProductList from the Shelf app and putting a custom wrapper around it.
You can see a custom "Related Products" shelf that is importing ProductList from vtex.shelf here: https://wordpress--storecomponents.myvtex.com/blog/post/13189
=> Make ProductList importable in other apps

CHANGELOG.md, react/queries/productsQuery.gql
Get the Product Properties in the Shelf
It should show the properties field in the Product.
[GraphiQL](https://camiloc--storecomponents.myvtex.com/_v/private/vtex.shelf@1.22.0/graphiql/v1?operationName=Products&variables=%7B%0A%20%20%22category%22%3A%20%22%22%2C%0A%20%20%22specificationFilters%22%3A%20%5B%5D%2C%0A%20%20%22orderBy%22%3A%20%22OrderByPriceDESC%22%2C%0A%20%20%22from%22%3A%200%2C%0A%20%20%22to%22%3A%209%0A%7D)
[Query (Too long)](https://paste.ofcode.org/PkPZwUTWbdnNKvzwuriYa3)
=> Add properties field in Products query

CHANGELOG.md, README.md, react/components/ProductList.js, react/components/ShelfContent.js, react/utils/propTypes.js
Add support for a `minItemsPerPage` prop to control the minimum number of items displayed on the Shelf, regardless of the client's screen size.
**This is dependent on https://github.com/vtex-apps/slider/pull/33 to work**
Gives the user control over how many items are shown on the smallest screen sizes
https://victorhmp--storecomponents.myvtex.com/
=> Minimum items per page

CHANGELOG.md, store/interfaces.json
As part of our new strategy for performance, we're testing the hypothesis that server side rendering shouldn't be sensible to segment. In the long run, we will fetch products server-side without generating a simulation and hydrate prices on the client-side. But for now, side-stepping server side rendering of the shelf should make the home page much faster immediately.
Slow server-side rendering.
N/A
=> Make shelf lazy

CHANGELOG.md, README.md, react/Shelf.js, react/components/ShelfContent.js
Add support for partially showing the next item on mobile through the `minItemsPerPage` prop, as the user can now pass a **Float** value to this prop, which is then rounded to the nearest multiple of 0.5 and used to set the initial `currentSlide`.
We do not support this feature right now. Although it is possible for the user to pass a float value to `minItemsPerPage`, that would result in strange behavior.
https://victorhmp--storecomponents.myvtex.com/ (on mobile)
=> Support for partially showing the next item on mobile

CHANGELOG.md, react/RelatedProducts.js
Fix a bug where the RelatedShelf component would not know if it was being rendered on mobile or not, always displaying the maximum amount of products.
Related products shelf broken on mobile.
https://relatedproductsbug--melimeloparis.myvtex.com/portofel-decor-2-bufnite/p
=> Fix related products shelf on mobile

CHANGELOG.md, manifest.json, react/queries/productRecommendations.gql, react/queries/productsQuery.gql
Use search-graphql in search queries.
Stop getting categories resolver in queries
https://messages--storecomponents.myvtex.com/apparel---accessories
https://search--exitocol.myvtex.com
https://search--samsungar.myvtex.com
https://search--alssports.myvtex.com/
https://search--parquedpedro.myvtex.com
https://search--newbalance.myvtex.com
https://search--naturitasit.myvtex.com
https://search--gc-wqp6166.myvtex.com/
=> use search graphql on search queries

CHANGELOG.md, store/interfaces.json
Make shelf assets subject to asset bundling and therefore load faster, instead of waiting for asset discovery during tree hydration.
Lazy is supposed to be used for components that might not be rendered.
=> Make shelf render strategy client

CHANGELOG.md, react/queries/productRecommendations.gql, react/utils/propTypes.js
The product brand was not appearing on a product's page's related products shelf
Now this is working as intended
[Workspace](https://iaronaraujo--gympassus.myvtex.com/concept2-rowerg%E2%84%A2-model-d-80/p)
=> Add brandId on productRecommendations

CHANGELOG.md, react/Shelf.js
After graphql typings when wild, we need to strictly type our query variables
=> forces hideUnavailableItems to be always a boolean

CHANGELOG.md, react/RelatedProducts.js
Read from `ProductList.schema` instead of calling `ProductList.getSchema(props)`.
Call to `undefined` function was breaking site-editor.
=> Fix related products schema by not using ProductList.getSchema

CHANGELOG.md, react/queries/productsQuery.gql
Add the `PriceWithoutDiscount` in the commertial offer field of the products query.
We need this value in the new minicart to calculate the totalizers for the order form when the user is offline.
[workspace](https://lucas--storecomponents.myvtex.com/).
=> Add PriceWithoutDiscount field in products query

CHANGELOG.md, react/RelatedProducts.js
`productImpression` event wasn't being sent for items on the `RelatedProducts` shelf. This PR fixes this.
[Workspace](https://iaronaraujo--alssports.myvtex.com/patagn-shirt-fitz-roy-horizons-resp/p)
See the related products shelf then go on console, type `pixelManagerEvents` and check that a `productImpression` event was sent with the products seen.
=> Fix impression events on `RelatedProducts`

CHANGELOG.md, react/components/ShelfItem.js
This hook isn't needed anymore since this logic was moved to the `product-summary`
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/)
Go to the console, type `pixelManagerEvents` and check that the `productImpression` events are still being sent correctly.
=> Removed `useInView`

CHANGELOG.md, react/RelatedProducts.js
The mobile view of the product detail page shows 5 items per row in the related product shelf. The `isMobile` prop passed by the `RelatedProducts` always carries the value `false` because of the order of object destructuring.
Check the related product shelf of the following workspace.
[Workspace](https://showtogether--sbdind.myvtex.com/robotic-welder-2/p)
=> Fix Number of Related Products in Mobile View

CHANGELOG.md, store/contentSchemas.json
The shelf had three blocks with the same ref to `#definitions/Shelf` in `contentSchemas.json`, and that schema had the `title` and `description` attributes, which is the thing that makes a block compliant with the new cms. So we are removing the description from this definition and create a new definition to related products
[site-editor with the changes made](https://cmscomponents2--storecomponents.myvtex.com/admin/cms/site-editor/)
[site-editor without the changes made](https://cmswithoutchanges--storecomponents.myvtex.com/admin/cms/site-editor/)
[new cms with the changes made](https://cmscomponents2--storecomponents.myvtex.com/admin/app/new-cms/edit/new)
[new cms without the changes made](https://cmswithoutchanges--storecomponents.myvtex.com/admin/app/new-cms/edit/new)
1. Open the …
=> Remove shelf blocks from the new cms

CHANGELOG.md, react/components/ShelfContent.js
Add class isActive to active dot.
https://produto--zonasul.myvtex.com/v-tto-fra-l-miquel-syrah-grenache-750ml/p
=> Add new CSS handle for the active dot

CHANGELOG.md, react/queries/productsQuery.gql
Our shelves are usign the product-spot-price and without this field on products it can't appears.
[Workspace](https://vtexshelf--carrefourbr.myvtex.com/dia-das-criancas-teste)
=> spotPrice to `Products` query.

CHANGELOG.md, react/queries/productRecommendations.gql
Add missing fields to productRecommendations query.
https://brenofield--sarachoneumaticos.myvtex.com/215-65-r16-michelin-primacy-4-102h/p
I considered #239, but we should test it more.
n/a
=> Add productClusters and spotPrice to productRecommendations

CHANGELOG.md, react/components/ShelfContent.js
Navigation arrows would not work when the `slider` was placed inside an `<a>` tag. This is the case if you were to place a `slider` inside of a `product-summary`. In our case, the `related-products` shelf is using the deprecated version of the slider.
[Workspace](https://createbundle--fstudioqa.myvtex.com/aparate-foto/aparate-foto-dslr/aparate-foto-dslr-profesionisti?map=departament,categorie,subcategorie)
Before:
After:
=> Stop event bubbling for navigation arrows

CHANGELOG.md, react/Shelf.js
maxItems prop was not being passed down to the list component
For it to work the user had to write the component like this:
```jsonc
{
"shelf#test": {
"blocks": [
"product-summary.shelf"
],
"props": {
"orderBy": "",
"category": "apparel---accessories",
"maxItems": 30, 
"productList": {
"maxItems": 30 // <--- this shouldn't be needed
}
}
}
}
```
This PR make it work like so:
```jsonc
{
"shelf#test": {
"blocks": [
"product-summary.shelf"
],
"props": {
"orderBy": "",
"category": "apparel---accessories",
"maxItems": 30
}
}
}
```
https://shelf--storecomponents.myvtex.com/
n/a
=> Fix prop maxItems not being passed down

CHANGELOG.md, react/queries/productRecommendations.gql
Fixed the product-highlights rendering problem inside a shelf.
[Workspace](https://plp--sbdsefuat.myvtex.com/ad68-612bs/p?__bindingAddress=catalog.sef.ao.sbd-nonprod.com/en-US/catalog-global)
Before 
After
Related to product-highlights
=> Add Cluster Highlights to Product Recommendations Query

CHANGELOG.md, docs/README.md, messages/context.json, messages/en.json, messages/es.json, messages/pt.json, react/RelatedProducts.js, react/utils/filterOutOfStock.js
Adds the possibility to hide out of stock products from RelatedProducts shelf
Link it to a dev workspace and add `hideOutOfStockItems` prop to any `shelf.relatedProducts`
[Workspace](https://claudiuhideunavailable--iviteb.myvtex.com/)
)
I've first tried to change the query by adding `isAvailablePerSalesChannel` param in search-resolver app, but it didn't worked.
=> Hideunavailable related products

CHANGELOG.md, docs/README.md
This PR adds deprecation warnings for the shelf.relatedProducts block. The block uses deprecated Catalog APIs to work, so using it shouldn't be advised. The team is working on a new block that uses stable APIs.
=> Deprecating shelf.relatedProducts block

CHANGELOG.md, docs/README.md
Clarify in the documentation which props belong to each component. For instance, it wasn't clear that the `hideOutOfStockItems` prop was associated only with the `RelatedProduct` component and that for the `Shelf` component, one should use the `hideUnavailableItems` props instead. By breaking the document in sections we can specify this better.
[Before](https://github.com/vtex-apps/shelf/blob/c4acc6231fa67ed7f6dfa2aa8e928d6d2ec2e331/docs/README.md#configuration)|[After](https://github.com/vtex-apps/shelf/blob/acb407d0f173054c12385b52fde755b4e9aa91a3/docs/README.md#configuration)
-|-
=> chore: Better clarify props for `Shelf` and `RelatedProducts`

CHANGELOG.md, docs/README.md, react/components/ProductList.js, react/components/ShelfContent.js, react/utils/propTypes.js
To add the "infinite" prop that will make users be able to choose whether they want the related products shelf be looped or not.
There is no way to make the related products shelf be non infinite.
You can see the "infinite": false example here (use mobile layout):
https://devalex--dunnesstores.myvtex.com/crew-neck-button-front-cardigan-8672766blac/p
Before
After
=> Add "infinite" property to the related products shelf
