vtex-apps/shelf

- storefront/components/Shelf.json
> Update resourceBinding to new storefront api

- src/components/Shelf/ShelfProduct.js
- src/components/Shelf/ShelfSlider.js
Depends on https://github.com/vtex-apps/storefront-sdk/pull/68
> Update SDK usage

- src/components/Shelf/Shelf.js
- src/components/Shelf/Shelf.less
- src/components/Shelf/ShelfSlider.js
- src/editors/ShelfEditor/ShelfEditor.js
- storefront/components/Shelf.json
This feature allows the user to list products by the id of a collection.
> Supports product collections

- src/components/Shelf/ShelfProduct.js
- src/components/Shelf/ShelfSlider.js
Depends on https://github.com/vtex-apps/storefront-sdk/pull/73
> Update Link from react-router to sdk

- src/components/Shelf/ShelfProduct/ShelfProduct.js
- src/components/Shelf/ShelfProduct/ShelfProduct.less
> Add responsive resize logic to ShelfProduct image

- .travis.yml
- README.md
- react/Shelf.js
- react/__test__/Shelf.test.js
- react/__test__/__snapshots__/Shelf.test.js.snap
Create the config file `.travis.yml` to integrate with CI. 
Integrate with a CI to improve the development process.
> Integrate with Travis CI

- react/Shelf.js
- react/package-lock.json
- react/package.json
Fix problem of deprecated Spinner Module
> Remove style prop of Spinner Component

- manifest.json
- react/ShelfContent.js
- react/global.css
Show all items on edit mode
https://shelf2--storecomponents.myvtex.com/shelf
> Update show all items on edit mode

- react/ShelfContent.js
- react/ShelfItem.js
- react/__mocks__/ProductSummary.js
- react/__mocks__/render.js
- react/__test__/Shelf.test.js
- react/__test__/__snapshots__/Shelf.test.js.snap
- react/global.css
- react/tests-setup.js
- Fix z-index of left arrow 
- Fix alignment of slide in ssr mode 
- Fix tests
https://shelf2--storecomponents.myvtex.com/shelf
> Fix z-index of left arrow | Fix alignment of slide in ssr mode

- CHANGELOG.md
- react/global.css
- Fix arrow right position
before
after
https://claudivan--storecomponents.myvtex.com/shelf
> Fix arrow right position

- CHANGELOG.md
- manifest.json
- react/ProductList.js
- react/Shelf.js
Add `isLayout` property to schema properties.
Lack of a way to separate fields that affect a component's layout from fields that modify its content.
- New feature (non-breaking change which adds functionality)
> Feature - isLayout property

- CHANGELOG.md
- react/ProductList.js
- react/__test__/Shelf.test.js
- react/package.json
Remove the title of Related ProductsList component when there's no related products.
Remove a title that appears in a page without any content to reference.
<a href="https://gustavo--storecomponents.myvtex.com/nintendo-switch/p">Workspace</a>
Before:
After:
> Fix Related Products

- CHANGELOG.md
- manifest.json
- react/queries/productsQuery.gql
- react/queries/relatedProductsQuery.gql
Adds stale cache for product preview
> Stale cache for product preview

- CHANGELOG.md
- manifest.json
Trying to make new release to break pages-graphql cache
> Release v0.17.5

- CHANGELOG.md
- react/ShelfContent.js
- react/ShelfItem.js
- react/propTypes.js
- Refactor ShelfItem.
- Pass ssrFallback to `Slider` component.
[workspace](https://claudivan2--storecomponents.myvtex.com/)
> Update ssrFallback to be injected into `Slider` component

- CHANGELOG.md
- react/ProductList.js
- react/ShelfContent.js
- react/package.json
- react/yarn.lock
Add the Shelf Content Loader.
Without the content loader, the spinner was shown.
[Access the workspace](https://estacio--storecomponents.myvtex.com/)
> Add Shelf Content Loader

- CHANGELOG.md
- manifest.json
Update the store-components version.
[Access the workspace.](https://waza3--storecomponents.myvtex.com/)
> Update the store-components version

- CHANGELOG.md
- manifest.json
- react/ProductList.js
- react/queries/productsQuery.gql
https://guilherme--vtexgame1.myvtex.com/
> Show unavailable products on shelf

- CHANGELOG.md
- manifest.json
- react/ShelfContent.js
- react/global.css
Fix product centering in devices with extra small screen, like Iphone 5 and SE.
Addressing design issues
[Accessing this workspace](https://fixproductspacing--storecomponents.myvtex.com/)
*Before*
*After*
> Fix product spacing in Iphone 5 and SE

- CHANGELOG.md
- manifest.json
- react/global.css
Fix slider dots different sizes on different apps
Different size for the slide dots
[Access this workspace](https://theoworkspace--storecomponents.myvtex.com/)
> Fix dots size on different components

- CHANGELOG.md
- README.md
- manifest.json
- react/ProductList.js
- react/__test__/Shelf.test.js
- react/locales/en-US.json
- react/locales/es-AR.json
- react/locales/pt-BR.json
- react/package.json
- react/yarn.lock
As the title says. 
Give a more meaningful title for the shelf. 
https://bruno--storecomponents.myvtex.com/
> Shelf title has intl

- CHANGELOG.md
- manifest.json
- react/package.json
https://next--storecomponents.myvtex.com/
> Update major version of storecomponents and product-summary

- CHANGELOG.md
- README.md
Update shelf readme.md with new options
> update shelf readme

- CHANGELOG.md
- manifest.json
- react/ShelfContent.js
As the title says
https://padding--storecomponents.myvtex.com/
> Add max-width on shelf Container

- CHANGELOG.md
- manifest.json
- react/Shelf.js
- react/ShelfContent.js
- react/__mocks__/vtex.store-components/Container.js
- react/global.css
Fix alignment on related products on mobile devices
[Access here](https://fixtheo--storecomponents.myvtex.com/st-tropez-shorts/p)
> Fix related products alignment

- CHANGELOG.md
- manifest.json
- react/global.css
As the title says
https://css--storecomponents.myvtex.com/
> Change Slider CSS tokens

- CHANGELOG.md
- manifest.json
> Release v1.5.3

- CHANGELOG.md
- manifest.json
- react/ProductList.js
- react/ShelfContent.js
- react/package.json
As title says.
[Access this workspace](https://galleryspace--storecomponents.myvtex.com/)
> Change Responsiveness implementation and add fixed gap between item.

- CHANGELOG.md
- manifest.json
- react/ShelfContent.js
- react/global.css
As title says.
Items with different heights in the shelf.
[Access this workspace](https://galleryspace--storecomponents.myvtex.com/)
> Align ShelfItems height.

- CHANGELOG.md
- manifest.json
- react/ShelfItem.js
As described in the title.
[Here](https://alves--storecomponents.myvtex.com/)
> Fix summary.name prop undefined when setting name tag

- CHANGELOG.md
- README.md
- manifest.json
- messages/context.json
- messages/en-US.json
- messages/es-AR.json
- messages/pt-BR.json
- react/ProductList.js
- react/ShelfItem.js
- react/propTypes.js
- store/interfaces.json
Also, add a prop `showTitle`
https://shelf--storecomponents.myvtex.com/
> Add product-summary as a block in interfaces.json

- react/package.json
- react/yarn.lock
> Add coveralls on dev dependencies

- CHANGELOG.md
- manifest.json
- store/interfaces.json
Track the clicks
.
https://felipem--storecomponents.myvtexdev.com/
> Add tracking for click events

- CHANGELOG.md
- manifest.json
- react/ShelfContent.js
As title says.
https://theotest--storecomponents.myvtex.com/
> Fix proptypes warnings

- CHANGELOG.md
- manifest.json
- react/ShelfContent.js
Add option on prop to slide per page or single.
This PR depends of [this one](https://github.com/vtex-apps/slider/pull/15)
[Access this workspace](https://slideadmin--storecomponents.myvtex.com/)
> Add slide per page option on slider

- CHANGELOG.md
- manifest.json
- react/ShelfItem.js
Fix the infinite Loading on the product.
When unavailable, the product keeps an infinite loading
[Workspace](https://theo--storecomponents.myvtex.com/)
Before:
After:
> Fix infinite loading product

- CHANGELOG.md
- manifest.json
- react/queries/productsQuery.gql
> uses new categoryTree property for products query

- CHANGELOG.md
- manifest.json
- react/Shelf.js
- react/package.json
- react/yarn.lock
- store/interfaces.json
Disables SSR on graphql query. Intended to be temporary.
The query it was doing looks to be a bit heavy. Should be slimmed down before going back on SSR.
Also adds preview on shelf interfaces.
Test on https://lbebber--storecomponents.myvtex.com/
> Disable ssr

- CHANGELOG.md
- manifest.json
- react/Shelf.js
- react/__test__/Shelf.test.js
Add test to when `Shelf` should show in Storefront and make it pass.
Shelf was hidden.
> Site editor visibility

- CHANGELOG.md
- manifest.json
- react/RelatedProducts.js
https://shelf--invictastores.myvtex.com/
> fix recommendation parse

- CHANGELOG.md
- manifest.json
Migrate to pixel-manager v1.
https://breno--storecomponents.myvtexdev.com/classy--sunglasses/p?disableUserLand
n/a
> Use pixel-manager v1

- CHANGELOG.md
- react/queries/productsQuery.gql
The PowerReviews app relies on this field to query for reviews.
https://breno--storecomponents.myvtex.com/
> Add productReference field to query

- CHANGELOG.md
- README.md
- messages/context.json
- messages/en.json
- messages/es.json
- messages/pt.json
- react/Shelf.js
https://fidelis--alssports.myvtex.com/
> allow usage of string on category prop

- README.md
> Add hideUnavailableItems prop to the readme

- CHANGELOG.md
- manifest.json
> Minify css rebuild

- CHANGELOG.md
- react/queries/productRecommendations.gql
- react/queries/productsQuery.gql
Show Teasers and Discounts in Shelf and Recommendation Shelf
[Query](https://paste.ofcode.org/MFyzw8P2fjnZDvjg4BmWRe)
[GraphiQL](https://vtexcamilo--exitocol.myvtex.com/_v/private/vtex.shelf@1.28.8/graphiql/v1?operationName=Products&variables=%7B%0A%20%20%22hideUnavailableItems%22%3A%20false%2C%0A%20%20%22category%22%3A%20%22%22%2C%0A%20%20%22collection%22%3A%20204%2C%0A%20%20%22specificationFilters%22%3A%20%5B%5D%2C%0A%20%20%22orderBy%22%3A%20%22%22%2C%0A%20%20%22from%22%3A%200%2C%0A%20%20%22to%22%3A%209%0A%7D)
[Workspace](https://vtexcamilo--exitocol.myvtex.com/)
> Add Discounts And Teasers Fields in Products And Recommendations Query

- CHANGELOG.md
- react/queries/productsQuery.gql
https://badge--storecomponents.myvtex.com/work-shirt/p
> add specification groups to products query

- CHANGELOG.md
- manifest.json
just remove store-graphql dep in manifest, not needed anymore
> remove store-graphql from deps

- CHANGELOG.md
- react/queries/productRecommendations.gql
- react/queries/productsQuery.gql
show price range based on resolver priceRange
https://pricerange--alssports.myvtex.com/
> use pricerange resolver

- CHANGELOG.md
- react/Shelf.js
- react/components/ProductList.js
- react/components/ProductListEventCaller.js
- react/components/ShelfItem.js
Fix the performance problem when clicking to see more items on the shelf.
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/)
> Fix performance on arrow click

- CHANGELOG.md
- docs/README.md
Update documentation to include implementation example using `list-context.product-list` and a `slider-layout`.
This documents the new way of implementing a Shelf.
https://github.com/vtex-apps/shelf/blob/chore/docs/docs/README.md
> Update documentation to include example implementation using product-list

- CHANGELOG.md
- react/queries/productRecommendations.gql
Return the productReference
Make it possible to use product-identifier using productReference in product recommendations shelf.
https://breno--bennemann.myvtex.com/pasta-couro-notebook-berlin-cafe/p
> Add productReference to ProductRecommendations query

- CHANGELOG.md
- react/queries/productRecommendations.gql
- react/queries/productsQuery.gql
- react/yarn.lock
Add new fields of Tax and taxPercentage.
Use the tax values in the product-price:
https://fernanda--cbcecub2c.myvtex.com/
> Add Tax and taxPercentage to queries

- CHANGELOG.md
- react/queries/productRecommendations.gql
- react/queries/productsQuery.gql
Add fields necessary to fix issue regarding fields being translated and changing the CSS classes applied.
Fixed:
https://breno--miriadeit.myvtex.com/?__bindingAddress=www.miriade.com/en
Class with `nero` applied:
Compare it with:
https://brenooff--miriadeit.myvtex.com/?__bindingAddress=www.miriade.com/en
Class with `black` was applied
none
Depends on https://github.com/vtex-apps/store-resources/pull/126
Depends on https://github.com/vtex-apps/store-components/pull/823
> Add skuSpecifications to queries

- CHANGELOG.md
- docs/README.md
> Add missing docs

- CHANGELOG.md
- react/RelatedProducts.js
- react/Shelf.js
- react/__mocks__/vtex.native-types/index.js
- react/components/ProductList.js
- react/components/ShelfContent.js
- react/components/ShelfItem.js
- react/utils/propTypes.js
This PR makes the shelf compatible with the new major of the GTM app.
[Workspace](https://icarogtm--storecomponents.myvtex.com/)
> Adding compatibility with new GTM major
